Revert "adb: add transport benchmark."
This reverts commit 5c0975ec12471bc6b5d8bd5716af77a64daf5307.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293